# Generated by Django 6.0.2 on 2026-02-27 18:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('financas', '0002_remove_receita_categoria_remove_receita_user_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='transacao',
            old_name='usuario',
            new_name='user',
        ),
    ]
