# Generated by Django 6.0.2 on 2026-03-06 21:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('financas', '0005_alter_formapagamento_user_alter_transacao_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='categoria',
            name='tipo',
            field=models.CharField(choices=[('receita', 'Receita'), ('despesa', 'Despesa')], default='despesa', max_length=10),
        ),
    ]
