# Generated by Django 6.0.2 on 2026-03-09 18:32

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('financas', '0006_categoria_tipo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='transacao',
            name='data',
            field=models.DateField(default=datetime.date.today),
        ),
    ]
