# Generated by Django 6.0.2 on 2026-03-09 19:12

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('financas', '0007_alter_transacao_data'),
    ]

    operations = [
        migrations.AlterField(
            model_name='transacao',
            name='data',
            field=models.DateField(blank=True, default=datetime.date.today, null=True),
        ),
    ]
